var temp = [
 [
"x                                                          x",
"x                                                          x",
"x                                                          x",
"x                                                          x",
"x                                                          x",
"x                                                          x",
"xxxxxxxwwwwwwx#                                            x",
"      xwwwwwwx#                                            x",
"      xwwwwwwx#                                            x",
"      xwwwwwwx#                                            x",
"      xwwwwwwx#                                            x",
"      xwwwwwwx#                                            x",
"      xwwwwwwx#                                            x",
"      xwwwwwwx#                                            x",
"      xwwwwwwx#                               #            x",
"      xwwwwwwx#                               #            x",
"      xwwwwwwx#                   oooo        #            x",
"      xwwwwwwx#                               #            x",
"      xxxxxxxxxxxxxppppxxxxxxxx  xxxxxx       #            x",
"                  x    x      x  xoooop       #            x",
"                  x    xxxxxx x  xoooop     xx#xxxxxxx     x",
"                  x         x x  xxxxxxxx      0           x",
"                  xoooooo   x x                            x",
"            xxxxxxxxxxxxxx #x x             s              x",
"            x      x     x #x xxxxxxxxxxxxxxxxx>   <xxxxxxxx",
"            x      x     x #x                  x   x        ",
"            x      x     x #x                  x!!!x        ",
"xxxxxxxxxxxxx      xxxxxxx #x                  x!!!x        ",
"x                          #x                  xxxxx        ",
"x                          #x                               ",
"xxxxxxxxxxxxx      xxxxxxx #x                               ",
"            x      x     x #x                               ",
"            x      x     x #x      xxxxxx  xxx              ",
"            x      x     x #x      x     xx  x              ",
"            x      x     x #x      x         x              ",
"            x      x     x #x      x   #x  xxx              ",
"            x      x     x #x      x   #     x              ",
"xxxxxxxxxxxxx      xxxxxxx #xxxxxxxx   #     x              ",
"x                          #         #xx     x              ",
"x                          #         #    xx x              ",
"x                          #         #       x              ",
"xwwwwwwwwwwwwwwwwwwwwwwwwww#wwwwwwwww#wwwwwwwx              ",
"xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx              ",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",
]
];
if (typeof module != "undefined" && module.exports)module.exports = temp;