
var LEVELS = [
 [
"xxxxxxxxxxxxWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                                       ",
"           xWWWWWWWWWWx#                                                       #               ",
"           xWWWWWWWWWWx#                                                       #               ",
"xxxxxxxxxxxxWWWWWWWWWWx#                                                       #               ",
"WWWWWWWWWWWWWWWWWWWWWWx#                                                       #               ",
"WWWWWWWWWWWWWWWWWWWWWWx#                                                       #               ",
"WWWWWWWWWWWWWWWWWWWWWWx#                                                       #               ",
"WWWWWWWWWWWWWWWWWWWWWWx#             @                                         #               ",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxPPPxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxx           xxx#xxxxxxxxxxx    ",
"                           x   x                    x    x      x              #               ",
"                           x   xxxxxxxxxxxxx        x    x oooo x              #               ",
"                           x               x        x    x oooo x              #               ",
"                           x               x        x    x      x                              ",
"                           x   o o o o     x        x    xxxxxxxxxxxxx                         ",
"                           x            #  x        x                                          ",
"                           xxxxxxxxxxxxx#xxx        x                                          ",
"                                     x  #  x        x                                          ",
"               xxxxxxxxxxxx          x  #  x        x                                          ",
"               x          x          x  #  x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxx",
"               x          x          x  #  x                                     x    x        ",
"               x          x          x  #  x                                     x    x        ",
"               x          x          x  #  x                                     x!!!!x        ",
"               x          x          x  #  x                                     xxxxxx        ",
"               x          x          x  #  x                                                   ",
"xxxxxxxxxxxxxxxx          xxxxxxxxxxxx  #  x                                                   ",
"                                        #  x                                                   ",
"                                        #  x                                                   ",
"                                        #  x                                                   ",
"                                        #  x                                                   ",
"xxxxxxxxxxxxxxxx          xxxxxxxxxxxx  #  x                                                   ",
"x              x          x          x  #  x                                                   ",
"x              x          x          x  #  x                                                   ",
"x              x          x          x  #  x                                                   ",
"x              x          x          x  #  x                                                   ",
"x              x          x          x  #  x                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
"x              x          x          x  #  x                  x                xxxxxx      x   ",
"x              x          x          x  #  x                  x                xxxxxx      x   ",
"x              x          x          x  #  x                  x                            x   ",
"x              x          x          x  #  x                  x                            x   ",
"x              x          x          x  #  x                  x         #xxxxxx      xxxxxxx   ",
"x              x          x          x  #  x                  x         #                  x   ",
"x              x          x          x  #  x                  x         #                  x   ",
"x              x          x          x  #  x                  x         #                  x   ",
"x              x          x          x  #  x                  x         #                  x   ",
"x              x          x          x  #  x                  x         #                  x   ",
"x              x          x          x  #  x                  x         #                  x   ",
"x              x          x          x  #  x                  x         #                  x   ",
"x              x          x          x  #  x                  x    #xxxxx                  x   ",
"xxxxxxxxxxxxxxxx          xxxxxxxxxxxx  #  xxxxxxxxxxxxxxxxxxxx    #                       x   ",
"x                                       #                          #                       x   ",
"x                                       #                          #                       x   ",
"x                                       #                          #              xxxxxx   x   ",
"x                                       #                          #                       x   ",
"x                                       #                          #                       x   ",
"xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#WWWWWWWWWWWWWWWWWWWWWWWWWW#WWWWWWWWWWWWWWWWWWWWWWWx   ",
"x      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
]
];
if (typeof module != "undefined" && module.exports)module.exports = LEVELS;
