var LEVELS = [
 [
"                                                                                           x                                                                                       ",
"                                                                                           x                                                                                       ",
"                                                                                           x                                                                                       ",
"                                                                                           x                                                                                       ",
"                                                                                           x                                                                                       ",
"                                                           #xxxxxxxxxxxxxxxxxxxxxxxxxPPPxxxx                                                                                       ",
"                                                           #                               x                                                                                       ",
"                                                           #                               x                                                                                       ",
"                                                           #                               x                                                                                       ",
"                                                           #                               x                                                                                       ",
"                                                           #                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                  ",
"                                                           #                               x      x                                             x                                  ",
"                                                           #                               x      x                                             x                                  ",
"                                                           _____                           x      P                                             x                                  ",
"                                                                                           x      P                                             x                                  ",
"                                                                   _____                   x      P                                             x                                  ",
"                                                                                           xxxxxxxxxxxxx#xxxxxxxxxxxxxxxxxx     xxxxxxx         x                                  ",
"                                                                           _____                  x     #                             x         x                                  ",
"                                                                                                  x     #                             x         x                                  ",
"                                                                                   xxxxxxxxxxx#   x     #                             x         x                                  ",
"                                                                                              #   x     #                             x         x                                  ",
"                                                                                              #   x     #                             x         x                                  ",
"                                                                                              #   x     #                             x         x                                  ",
"                                                                                              #   x     #                             x         x                                  ",
"                                                                                              #   x     #                             xxxxxxxxxxx                                  ",
"                                                                                              #   xxxxxxxxxx                                    x                                  ",
"                                                                          #xxxxxxxx     xxxxxxx   x        x                                    x                                  ",
"                                                                          #                       x        x                                    x                                  ",
"                                                                          #                       x        xxxxxxxxxx                           x                                  ",
"                                                                          #                       x                 x                           x                                  ",
"xxxxxxxxxxxxwwwwwwwwwwx#                                                  #                       x                 x                                                              ",
"           xwwwwwwwwwwx#                                                  #                       x                 xxxxxxxxxx                                                     ",
"           xwwwwwwwwwwx#                                                  #                       x                          x                                                     ",
"           xwwwwwwwwwwx#                                                  xxxxxxx    xxxxxx       x                          x               x                                     ",
"           xwwwwwwwwwwx#                                                                      ____xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#xxxx          xxxxxxx                 ",
"           xwwwwwwwwwwx#                                                                          x                                         #                                      ",
"           xwwwwwwwwwwx#                                                                          x                                         #                                      ",
"           xwwwwwwwwwwx#                                                                          x                                         #                                      ",
"           xwwwwwwwwwwx#                                                      xxxxxxxxxx  #xxxxxxxx                                         #                                      ",
"           xwwwwwwwwwwx#                                                       #          #                                                 #                                      ",
"           xwwwwwwwwwwx#                                                       #          #                                                 #                                      ",
"           xwwwwwwwwwwx#                                                       #          #                                                 #                                      ",
"           xwwwwwwwwwwx#                                                       #          #                                                 #                                      ",
"xxxxxxxxxxxxwwwwwwwwwwx#                                                       #          #                                                 #                                      ",
"wwwwwwwwwwwwwwwwwwwwwwx#                                                       #          #                                                 #                                      ",
"wwwwwwwwwwwwwwwwwwwwwwx#                                                       #          #                                          xxxxxxx#                                      ",
"wwwwwwwwwwwwwwwwwwwwwwx#                                                       #          #                      #xxxxxxxxx     xxxx        #                                      ",
"wwwwwwwwwwwwwwwwwwwwwwx#             @                                      xxx#xxxxxxxxxxx                      #                          #                                      ",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxPPPxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxx              #                                 #                          #                                      ",
"                           x   x                    x    x      x              #                                 #                          #                                      ",
"                           x   xxxxxxxxxxxxx        x    x oooo x              #                                 #                     xxxxxxxx                                    ",
"                           x__             x        x    x oooo x                                                #                                                                 ",
"                           x               x        x    x      x                                                #                                                                 ",
"                           x   o o o o     x        x    xxxxxxxxxxxxx                                           #                                                                 ",
"                           x            #  x        x                                                            #                                                                 ",
"                           xxxxxxxxxxxxx#xxx        x                                                            #                                                                 ",
"                                     x  #  x        x                                                            #                                                                 ",
"               xxxxxxxxxxxx          x  #  x        x                                                            #                                                                 ",
"               x          x          x  #  x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxwwwwwwwwwwwwwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"               x          x          h  #  x                                     x     x                                         xwwwwwwwwwwwwwwx                                  ",
"               x          x          x  #  x                                     x     x                                         xwwwwwwwwwwwwwwx                                  ",
"               x          x          x  #  x                                     x!!!!!x                                         xwwwwwwwwwwwwwwx                                  ",
"               x          x          x  #  k                                     xxxxxxx                                         xwwwwwwwwwwwwwwx                                  ",
"               x          x          x  #  x                                                                                     xwwwwwwwwwwwwwwx                                  ",
"xxxxxxxxxxxxxxxx          xxxxxxxxxxxi  #  x                                                                                     xwwwwwwwwwwwwwwx                                  ",
"                                        #  x                                                                                     xwwwwwwwwwwwwwwx                                  ",
"                                        #  x                                                                                     xwwwwwwwwwwwwwwx                                  ",
"                                        #  x                                                                                     xwwwwwwwwwwwwwwx                                  ",
"                                        #  x                                                                                     xwwwwwwwwwwwwwwx                                  ",
"xxxxxxxxxxxxxxxx          xxxxxxxxxxxx  #  x                                                                                                                                       ",
"x              x          x          x  #  x                                                                                                                                       ",
"x              x          x          x  #  x                                                                                                                                       ",
"x              x          x          x  #  x                                                                                                                                       ",
"x              x          x          x  #  x                                                                                                                                       ",
"x              x          x          x  #  x                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                       ",
"x              x          x          x  #  x                  x                xxxxxx      x                                                                                       ",
"x              x          x          x  #  x                  x                xxxxxx      x                                                                                       ",
"x              x          x          x  #  x                  x                            x                                                                                       ",
"x              x          x          x  #  x                  x                            x                                                                                       ",
"x              x          x          x  #  x                  x         #xxxxxx      xxxxxxx                                                                                       ",
"x              x          x          x  #  x                  x         #                  x                                                                                       ",
"x              x          x          x  #  x                  x         #                  x                                                                                       ",
"x              x          x          x  #  x                  x         #                  x                                                                                       ",
"x              x          x          x  #  x                  x         #                  x                                                                                       ",
"x              x          x          x  #  x                  x         #                  x                                                                                       ",
"x              x          x          x  #  x                  x         #                  x                                                                                       ",
"x              x          x          x  #  x                  x         #                  x                                                                                       ",
"x              x          x          x  #  x                  x    #xxxxx                  x                                                                                       ",
"xxxxxxxxxxxxxxxx          xxxxxxxxxxxx  #  xxxxxxxxxxxxxxxxxxxx    #                       x                                                                                       ",
"x                                       #                          #                       x                                                                                       ",
"x                                       #                          #                       x                                                                                       ",
"x                                       #                          #              xxxxxx   x                                                                                       ",
"x                                       #                          #                       x                                                                                       ",
"x                                       #                          #                       x                                                                                       ",
"xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww#wwwwwwwwwwwwwwwwwwwwwwwwww#wwwwwwwwwwwwwwwwwwwwwwwx                                                                                       ",
"x      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                       ",
]
];
if (typeof module != "undefined" && module.exports)module.exports = LEVELS;
