var LEVEL_A = [
 [
"xxxxxwwwwx#              #         ",
"    xwwwwx#              #         ",
"    xwwwwx#              #         ",
"    xwwwwx#              #         ",
"    xwwwwx#              #         ",
"    xwwwwx#              #         ",
"    xwwwwx#              #         ",
"    xwwwwx#             x#xxxxx    ",
"    xwwwwx#              # s       ",
"xxxxxwwwwx#              #         ",
"wwwwwwwwwx#              #         ",
"wwwwwwwwwx#                        ",
"wwwwwwwwwx#   @                    ",
"xxxxxxxxxxxx#xxxx xxx              ",
"           x x xx xoo              ",
"           x x xx x  s             ",
"           x x xx xxxx             ",
"           xoo xx                  ",
"           xoo xxxxxxxxxxx   xxxxxx",
"           xxx#x         x   x     ",
"             x#x         x   x     ",
"       xxxx  x#x         x   x     ",
"       x  x  x#x         x   x     ",
"       x  x  x#x         x   x     ",
"   xxxxx  xxxx#x         xwwwx     ",
"              #x  xxxxxxxxxxxx     ",
"              #x  x xx  x          ",
"              #x  x     x          ",
"              #x  x     x          ",
"   xxxxx  xxx #x  x#x  xx          ",
"   xxxxx  xxx #x  x#    x          ",
"   xxxxx  xxx #xxxx#    x          ",
"              #    #    x          ",
"              #    #    x          ",
"              #  #xx  x x          ",
"              #  #      x          ",
"              #  #      x          ",
"   wwwwwwwwwww#wwwwwwwwwx          ",
"   wwxxxxxxxxxxxxxxxxxxxx          ",
"   ww                              ",
"   ww                              ",
]
];
if (typeof module != "undefined" && module.exports)module.exports = LEVEL_A;